namespace VibeCode.Services;

/// <summary>
/// The turns that are still being generated, so the telemetry windows can show a turn WHILE it streams instead
/// of only after it lands.
///
/// <see cref="UsageLog"/> is deliberately a record of COMMITTED turns - one line per finished turn, appended to
/// a file that outlives the session. That is the right shape for history and the wrong shape for a wall someone
/// is watching: every figure on it sat frozen for the whole of a long turn and then jumped at the end, which on
/// a window whose entire job is to look live reads as a broken window rather than an idle one.
///
/// This holds the missing piece - each chat's current, uncommitted turn - as provisional rows a watcher can lay
/// over the committed history. Nothing here is ever persisted: a row lives until its turn commits (at which
/// point the real entry replaces it in the log), until its chat closes, or until it goes stale.
///
/// It is PULL, not push. A chat hands over a snapshot; nothing is raised, no dispatcher work is queued, no
/// timer runs. Watchers read <see cref="Merge"/> and <see cref="OutputTokensPerSecond"/> on their own clock.
/// Streaming is token-rate traffic - pushing an event per snapshot would put a UI repaint behind every few
/// tokens generated, which is exactly the lag this window cannot afford.
///
/// And it is OFF unless something is watching. <see cref="IsWatched"/> is a single volatile read, and it is the
/// first thing <see cref="Report"/> does: with the wall and HUD closed - the overwhelmingly common case - the
/// entire cost of all this to a streaming turn is one branch per usage snapshot.
/// </summary>
public sealed class LiveTurnTelemetry
{
    public static LiveTurnTelemetry Instance { get; } = new();

    /// <summary>Tokens per second is averaged over this much recent generation. Long enough that the figure is
    /// readable rather than jittering with every snapshot, short enough that it still tracks a model changing
    /// pace. Also the decay: once generation stops, the rate falls to zero across this window rather than
    /// dropping out of the display the instant a turn ends.</summary>
    private static readonly TimeSpan RateWindow = TimeSpan.FromSeconds(6);

    /// <summary>A live row this old is dropped on the next read. The backstop for a chat that went away without
    /// saying so - a crashed provider process, a window torn down mid-turn. Generously longer than any gap
    /// between snapshots inside a turn that is genuinely still running.</summary>
    private static readonly TimeSpan Stale = TimeSpan.FromSeconds(45);

    /// <summary>How far back <see cref="Flow"/> reaches. Sized for the widest live panel the wall draws
    /// (60 bars of 10 seconds = 10 minutes) plus a minute of slack, so the oldest bar is never half-empty
    /// because its samples aged out between the build and the render.</summary>
    private static readonly TimeSpan FlowWindow = TimeSpan.FromMinutes(11);

    /// <summary>One chat's in-flight turn. Replaced wholesale on every snapshot rather than mutated, so a
    /// <see cref="Merge"/> already holding the old instance can never see a half-updated row.</summary>
    private sealed class LiveRow
    {
        public required UsageEntry Entry { get; init; }
        public required DateTime Updated { get; init; }
    }

    private readonly object _gate = new();
    private readonly Dictionary<object, LiveRow> _rows = new(ReferenceEqualityComparer.Instance);
    /// <summary>(when, total output generated by then). Only ever grows on the right; trimmed from the left.</summary>
    private readonly Queue<(DateTime At, double Total)> _samples = new();
    /// <summary>
    /// The token flow itself: one row per snapshot, carrying what arrived SINCE the previous snapshot rather
    /// than the turn's running total, stamped when it was observed.
    ///
    /// That difference is the whole point. <see cref="UsageLog"/> stamps a turn's entire token count at the
    /// instant it COMMITS, which is the right shape for history and useless at second resolution: a four-minute
    /// turn lands as one spike in whichever second it happened to finish in. These rows spread the same tokens
    /// across the seconds they were actually generated in, which is what a real-time graph has to plot.
    ///
    /// Deltas rather than totals also make the rows summable, and every derived figure - cost, electricity,
    /// water - is strictly linear in the four token counts (see <see cref="ModelPricing.TurnCost"/> and
    /// <see cref="ModelEnergy.TurnEnergyWh"/>), so a turn split across forty rows still totals to exactly what
    /// the one committed row says.
    /// </summary>
    private readonly Queue<UsageEntry> _flow = new();
    /// <summary>Every output token seen since the process started. MONOTONIC on purpose: a turn committing
    /// removes its row, and if the rate were taken from the live total instead it would read that removal as a
    /// burst of negative generation.</summary>
    private double _outputSeen;
    private int _watchers;

    private LiveTurnTelemetry() { }

    /// <summary>True while at least one telemetry window is open. Read on the streaming path, so it is a plain
    /// volatile int rather than anything that could contend.</summary>
    public bool IsWatched => Volatile.Read(ref _watchers) > 0;

    /// <summary>
    /// Arm live tracking for as long as the returned handle is held. Dispose it when the window closes; the last
    /// one out drops every row, so a window reopened later never starts on somebody's abandoned turn.
    /// </summary>
    public IDisposable Watch() => new Watcher(this);

    private sealed class Watcher : IDisposable
    {
        private LiveTurnTelemetry? _owner;

        public Watcher(LiveTurnTelemetry owner)
        {
            _owner = owner;
            Interlocked.Increment(ref owner._watchers);
        }

        public void Dispose()
        {
            // Null it first: a double Dispose (Closed can be raised more than once for a window that is also
            // being disposed) would otherwise take the count below zero and disarm a wall that is still open.
            var owner = Interlocked.Exchange(ref _owner, null);
            if (owner is null) return;
            if (Interlocked.Decrement(ref owner._watchers) > 0) return;
            lock (owner._gate)
            {
                owner._rows.Clear();
                owner._samples.Clear();
                owner._flow.Clear();
            }
        }
    }

    /// <summary>
    /// Publish one chat's current turn. <paramref name="output"/> and the input figures are the turn's running
    /// TOTALS, not deltas - the same cumulative snapshot the chat header is drawn from - so a snapshot that
    /// arrives twice, or out of order, cannot inflate anything.
    /// </summary>
    /// <param name="owner">The chat this turn belongs to. Identity only; never dereferenced.</param>
    public void Report(object owner, string provider, string? model, double input, double cacheWrite,
        double cacheRead, double output, string? sessionId, string? project)
    {
        if (!IsWatched) return;

        input = Math.Max(0, input);
        cacheWrite = Math.Max(0, cacheWrite);
        cacheRead = Math.Max(0, cacheRead);
        output = Math.Max(0, output);
        if (input + cacheWrite + cacheRead + output <= 0) { Clear(owner); return; }

        var id = ModelPricing.CanonicalId(model);
        var now = DateTime.UtcNow;
        var entry = new UsageEntry
        {
            At = DateTimeOffset.Now,
            Provider = string.IsNullOrWhiteSpace(provider) ? "claude" : provider,
            Model = string.IsNullOrWhiteSpace(id) ? "unknown" : id,
            Input = input,
            CacheWrite = cacheWrite,
            CacheRead = cacheRead,
            Output = output,
            // Nothing reports a price mid-turn, so this is the list-price estimate by definition. It is replaced
            // wholesale by the committed row - including a provider-reported one - the moment the turn lands.
            CostUsd = Math.Max(0, ModelPricing.TurnCost(id, input, cacheWrite, cacheRead, output)),
            CostReported = false,
            SessionId = sessionId,
            Project = project,
        };

        lock (_gate)
        {
            // What arrived since this chat's last snapshot. A total that went DOWN is a new turn under the same
            // chat, not tokens being un-generated: count the whole of the new figure rather than a negative
            // delta. Taken per bucket rather than on the total, because a new turn can be smaller than the last
            // in one bucket and larger in another - a single comparison on the total would then post a negative
            // step for the bucket that shrank.
            var last = _rows.TryGetValue(owner, out var previous) ? previous.Entry : null;
            var stepIn = Step(input, last?.Input);
            var stepWrite = Step(cacheWrite, last?.CacheWrite);
            var stepRead = Step(cacheRead, last?.CacheRead);
            var stepOut = Step(output, last?.Output);

            _outputSeen += stepOut;
            _rows[owner] = new LiveRow { Entry = entry, Updated = now };

            _samples.Enqueue((now, _outputSeen));
            if (stepIn + stepWrite + stepRead + stepOut > 0)
            {
                // Priced from the DELTA, not from the turn so far, or the flow would re-bill the whole prompt on
                // every snapshot. Both this and the energy the buckets derive are linear in the token counts, so
                // the rows still sum to exactly what the committed turn is worth.
                _flow.Enqueue(new UsageEntry
                {
                    At = entry.At,
                    Provider = entry.Provider,
                    Model = entry.Model,
                    Input = stepIn,
                    CacheWrite = stepWrite,
                    CacheRead = stepRead,
                    Output = stepOut,
                    CostUsd = Math.Max(0, ModelPricing.TurnCost(id, stepIn, stepWrite, stepRead, stepOut)),
                    CostReported = false,
                    SessionId = sessionId,
                    Project = project,
                });
            }
            TrimLocked(now);
        }
    }

    /// <summary>One bucket's arrival since the last snapshot of the same turn.</summary>
    private static double Step(double now, double? then) => then is { } was && now >= was ? now - was : now;

    /// <summary>Drop this chat's live row - its turn committed, was interrupted, or the chat closed. Safe to
    /// call for a chat that never reported anything.</summary>
    public void Clear(object owner)
    {
        lock (_gate)
        {
            _rows.Remove(owner);
        }
    }

    /// <summary>How many turns are generating right now. Zero is the idle state every watcher paints.</summary>
    public int StreamingCount
    {
        get { lock (_gate) { DropStaleLocked(DateTime.UtcNow); return _rows.Count; } }
    }

    /// <summary>Output tokens per second across every streaming turn, averaged over <see cref="RateWindow"/>.
    /// Zero when nothing has generated recently - this is a measured rate, not a guess, so an idle machine gets
    /// a zero rather than the last figure it happened to reach.</summary>
    public double OutputTokensPerSecond
    {
        get
        {
            var now = DateTime.UtcNow;
            lock (_gate)
            {
                TrimLocked(now);
                if (_samples.Count < 2) return 0;
                // The newest sample is _outputSeen by construction - the counter only ever moves forward, and
                // every move enqueues its new value - so the right edge does not need looking up.
                var first = _samples.Peek();
                var generated = _outputSeen - first.Total;
                if (generated <= 0) return 0;
                // Measured against NOW rather than the last sample, so a turn that stalls mid-generation shows
                // the rate falling instead of holding whatever it managed before it stopped. The floor stops a
                // burst that arrives inside a few milliseconds from reporting an implausible figure.
                var elapsed = Math.Max(0.5, (now - first.At).TotalSeconds);
                return generated / elapsed;
            }
        }
    }

    /// <summary>Tokens generated so far by the turns currently in flight - the "and how big is this one getting"
    /// figure that a rate alone does not answer.</summary>
    public double StreamingTokens
    {
        get
        {
            var now = DateTime.UtcNow;
            lock (_gate)
            {
                DropStaleLocked(now);
                double total = 0;
                foreach (var row in _rows.Values) total += row.Entry.Total;
                return total;
            }
        }
    }

    /// <summary>
    /// <paramref name="committed"/> with every in-flight turn laid on top, oldest first - what a watcher should
    /// aggregate instead of the log alone.
    ///
    /// Returns the caller's own list untouched when nothing is streaming, which is the case on every refresh of
    /// an idle wall: the common path allocates nothing and copies nothing.
    /// </summary>
    public IReadOnlyList<UsageEntry> Merge(IReadOnlyList<UsageEntry> committed)
    {
        var now = DateTime.UtcNow;
        lock (_gate)
        {
            DropStaleLocked(now);
            if (_rows.Count == 0) return committed;
            var merged = new List<UsageEntry>(committed.Count + _rows.Count);
            merged.AddRange(committed);
            foreach (var row in _rows.Values) merged.Add(row.Entry);
            // The log is oldest-first and every consumer of it assumes that. A live row is stamped now, so this
            // only ever has to fix the tail, but sorting says it rather than relying on it.
            merged.Sort(static (a, b) => a.At.CompareTo(b.At));
            return merged;
        }
    }

    /// <summary>
    /// Tokens as they ARRIVED over the last <see cref="FlowWindow"/>, oldest first: one row per snapshot,
    /// each carrying only what was new at that instant. Aggregate it with
    /// <see cref="UsageAnalytics.BuildBuckets"/> exactly like the committed log.
    ///
    /// Never mix this with <see cref="Merge"/> or the log itself - the same tokens are in both, once as the
    /// seconds they streamed over and once as the turn that committed them, and summing the two double-counts
    /// every turn the wall watched land.
    /// </summary>
    public IReadOnlyList<UsageEntry> Flow()
    {
        var now = DateTime.UtcNow;
        lock (_gate)
        {
            TrimFlowLocked();
            return _flow.Count == 0 ? Array.Empty<UsageEntry>() : _flow.ToArray();
        }
    }

    private void TrimLocked(DateTime now)
    {
        var cutoff = now - RateWindow;
        while (_samples.Count > 0 && _samples.Peek().At < cutoff) _samples.Dequeue();
        TrimFlowLocked();
        DropStaleLocked(now);
    }

    /// <summary>Age flow rows out of the ring. Compared as <see cref="DateTimeOffset"/>s, i.e. on the absolute
    /// instant, so a machine that changes offset mid-session cannot make the ring look either empty or
    /// unbounded.</summary>
    private void TrimFlowLocked()
    {
        if (_flow.Count == 0) return;
        var cutoff = DateTimeOffset.UtcNow - FlowWindow;
        while (_flow.Count > 0 && _flow.Peek().At < cutoff) _flow.Dequeue();
    }

    private void DropStaleLocked(DateTime now)
    {
        if (_rows.Count == 0) return;
        List<object>? dead = null;
        foreach (var (owner, row) in _rows)
            if (now - row.Updated > Stale)
                (dead ??= new List<object>()).Add(owner);
        if (dead is null) return;
        foreach (var owner in dead) _rows.Remove(owner);
    }
}
