using System.IO;
using System.Reflection;
using NAudio.Wave;

namespace VibeCode.Services;

/// <summary>One selectable notification sound: either a chime bundled in the exe or a file the user dropped in.</summary>
/// <param name="Id">Stable key written to settings. For bundled sounds this is the asset's file stem.</param>
/// <param name="Name">What the picker shows.</param>
/// <param name="Resource">Embedded resource name, for bundled sounds.</param>
/// <param name="Path">Absolute path, for user-supplied files.</param>
public sealed record NotificationSound(string Id, string Name, string? Resource, string? Path)
{
    public bool IsCustom => Path is not null;
    public bool IsSilent => Resource is null && Path is null;
    /// <summary>Tag shown beside user-supplied files. Empty for the bundled set, so the picker
    /// template can bind straight to it without needing a visibility converter.</summary>
    public string Badge => IsCustom ? "yours" : "";
}

/// <summary>
/// The catalogue of notification chimes and the one place that plays them.
///
/// Three sources, in the order the picker lists them: silence, the bundled set under
/// <c>Assets/Sounds</c> (generated by <c>_gen_sounds.py</c>, all under four seconds), and anything the user
/// has dropped into <see cref="UserDir"/>. That last folder is the supported way to add your own — download
/// whatever you like from Pixabay or elsewhere, drop the files in, and they appear in the list beside the
/// built-ins. Formats follow whatever NAudio can open: WAV and MP3 certainly, WMA/AIFF in practice.
/// </summary>
public static class NotificationSounds
{
    /// <summary>Chosen when the user wants toasts to appear silently.</summary>
    public const string SilentId = "silent";

    /// <summary>The original bundled Mixkit chime, kept so existing installs sound unchanged.</summary>
    public const string ClassicId = "classic";

    public const string DefaultId = ClassicId;

    private const string AssetPrefix = "VibeCode.Assets.Sounds.";

    private static readonly string[] PlayableExtensions = [".wav", ".mp3", ".wma", ".aiff", ".aif", ".m4a"];

    /// <summary>Drop your own chimes here; they show up in the picker next to the bundled ones.</summary>
    public static string UserDir => System.IO.Path.Combine(AppSettings.Dir, "Sounds");

    private static IReadOnlyList<NotificationSound>? _cache;

    public static IReadOnlyList<NotificationSound> All => _cache ??= Build();

    /// <summary>Re-scan the user folder — call after the user has added files.</summary>
    public static void Refresh() => _cache = null;

    public static NotificationSound Resolve(string? id) =>
        All.FirstOrDefault(s => string.Equals(s.Id, id, StringComparison.OrdinalIgnoreCase))
        ?? All.FirstOrDefault(s => s.Id == DefaultId)
        ?? All[0];

    private static IReadOnlyList<NotificationSound> Build()
    {
        var list = new List<NotificationSound>
        {
            new(SilentId, "Silent (no sound)", null, null),
            new(ClassicId, "Classic", "VibeCode.Assets.notification.mp3", null),
        };

        // Bundled set. Names are "NN-kebab-case.wav" purely so they list in a sensible
        // order; the number is stripped for display and the stem is the saved id.
        var bundled = Assembly.GetExecutingAssembly().GetManifestResourceNames()
            .Where(n => n.StartsWith(AssetPrefix, StringComparison.Ordinal))
            .OrderBy(n => n, StringComparer.Ordinal);
        foreach (var res in bundled)
        {
            var stem = System.IO.Path.GetFileNameWithoutExtension(res[AssetPrefix.Length..]);
            list.Add(new NotificationSound(stem, PrettyName(stem), res, null));
        }

        foreach (var file in UserFiles())
        {
            var stem = System.IO.Path.GetFileNameWithoutExtension(file);
            // "custom:" keeps a user file called 06-marimba.wav from shadowing the bundled one.
            list.Add(new NotificationSound("custom:" + stem, PrettyName(stem), null, file));
        }

        return list;
    }

    private static IEnumerable<string> UserFiles()
    {
        try
        {
            if (!Directory.Exists(UserDir)) return [];
            return Directory.EnumerateFiles(UserDir)
                .Where(f => PlayableExtensions.Contains(System.IO.Path.GetExtension(f), StringComparer.OrdinalIgnoreCase))
                .OrderBy(f => f, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException)
        {
            return [];   // an unreadable folder must not cost the user their picker
        }
    }

    /// <summary>"03-tubular" -> "Tubular"; "my_cool sound" -> "My Cool Sound".</summary>
    private static string PrettyName(string stem)
    {
        var s = stem;
        var dash = s.IndexOf('-');
        if (dash > 0 && s[..dash].All(char.IsDigit)) s = s[(dash + 1)..];
        s = s.Replace('-', ' ').Replace('_', ' ');
        var words = s.Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Select(w => char.ToUpperInvariant(w[0]) + (w.Length > 1 ? w[1..] : ""));
        var joined = string.Join(' ', words);
        return string.IsNullOrWhiteSpace(joined) ? stem : joined;
    }

    // ---------------- playback ----------------

    /// <summary>Bumped when a sound starts so an older play-loop stops early instead of stacking chimes.</summary>
    private static int _generation;

    /// <summary>Play a sound by id, off the UI thread. Never throws: audio is optional chrome.</summary>
    public static void Play(string? id, float volume = 0.7f) => Play(Resolve(id), volume);

    public static void Play(NotificationSound sound, float volume = 0.7f)
    {
        if (sound.IsSilent) { Interlocked.Increment(ref _generation); return; }

        var gen = Interlocked.Increment(ref _generation);
        _ = Task.Run(() =>
        {
            try
            {
                using var reader = Open(sound);
                if (reader is null) return;

                using var output = new WaveOutEvent();
                output.Volume = Math.Clamp(volume, 0f, 1f);
                output.Init(reader);
                output.Play();
                while (output.PlaybackState == PlaybackState.Playing)
                {
                    // A newer sound won the race — stop rather than layering.
                    if (gen != Volatile.Read(ref _generation))
                    {
                        try { output.Stop(); } catch { /* already gone */ }
                        break;
                    }
                    Thread.Sleep(20);
                }
            }
            catch { /* a missing or corrupt chime must never block a toast */ }
        });
    }

    /// <summary>Stop whatever is currently playing (the play-loop notices the generation bump).</summary>
    public static void Stop() => Interlocked.Increment(ref _generation);

    private static WaveStream? Open(NotificationSound sound)
    {
        if (sound.Path is { } path)
            return File.Exists(path) ? new AudioFileReader(path) : null;   // handles wav/mp3/wma/…

        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(sound.Resource!);
        if (stream is null) return null;

        // Both readers need to seek, and a manifest resource stream may not; copy once.
        var ms = new MemoryStream((int)Math.Min(stream.Length, int.MaxValue));
        stream.CopyTo(ms);
        ms.Position = 0;

        return sound.Resource!.EndsWith(".mp3", StringComparison.OrdinalIgnoreCase)
            ? new Mp3FileReader(ms)
            : new WaveFileReader(ms);
    }
}
