package com.vibecode.mobile.data

import android.content.Context
import org.json.JSONObject

/**
 * The PC this copy of the app was built for.
 *
 * A generic APK downloaded from anywhere has `configured = false` and behaves like a normal app: the user types
 * an address and a pairing code. An APK generated by a desktop has this filled in, which means it already knows
 * which machine it belongs to, which certificate that machine must present, and a one-shot secret it can trade
 * for a real credential without the user typing anything.
 *
 * The [fingerprint] is the important field. It is baked into a signed APK, so it cannot be edited without
 * breaking the signature, and the app refuses for the rest of its life to talk to any machine presenting a
 * different certificate — including one that answers on the same address later.
 */
data class EnrolmentConfig(
    val configured: Boolean,
    val hosts: List<String>,
    val port: Int,
    val fingerprint: String,
    val pcName: String,
    val secret: String,
) {
    companion object {
        private const val ASSET = "vibecode-enroll.vcenroll"

        /** Reads the baked configuration, or null when this is a generic build. */
        fun load(context: Context): EnrolmentConfig? = runCatching {
            val raw = context.assets.open(ASSET).use { it.readBytes() }
                .toString(Charsets.UTF_8)
                // The slot is a fixed size and space-padded by the desktop so the APK's zip entry never changes
                // length; the padding is not part of the JSON.
                .trim()
            val o = JSONObject(raw)
            if (!o.optBoolean("configured")) return null

            val hostArray = o.optJSONArray("hosts")
            val hosts = (0 until (hostArray?.length() ?: 0)).mapNotNull { hostArray?.optString(it) }
                .filter { it.isNotBlank() }

            val config = EnrolmentConfig(
                configured = true,
                hosts = hosts,
                port = o.optInt("port", 8765),
                fingerprint = o.optString("fingerprint"),
                pcName = o.optString("pcName"),
                secret = o.optString("secret"),
            )
            // A half-filled slot is worse than none: it would send the app looking for a PC it cannot verify.
            if (config.hosts.isEmpty() || config.fingerprint.length != 64) null else config
        }.getOrNull()
    }
}
